site_name: Исследовательские материалы
site_description: Публикация результатов исследований и практических заданий
site_url: !ENV [SITE_URL, 'https://l1oness.github.io/project-python/']
repo_url: https://github.com/L1oneSs/project-python
repo_name: Исходный код

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Тёмная тема

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false
strict: true
nav:
  - Главная: index.md
  - Подходы к публикации: publication-methods.md
  - T1. Сравнительный анализ генераторов: t1.md
  - P2. Стресс-тест научного контента: p2.md